security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        myProvider:
            entity: { class: App\Entity\User, property: username }
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # logout:
            #     path: /logout
            #     target: /login
            # logout_on_user_change: true

            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator
        #access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
